<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://beautycare.com/api/ws/clientes"
           xmlns:tns="http://beautycare.com/api/ws/clientes"
           elementFormDefault="qualified">

    <xs:element name="ConsultarEstadoClienteRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="clienteId" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="ConsultarEstadoClienteResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="estadoCliente" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>